version: "3.3"
services:

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - client-contacts
    environment:
      DB_HOST: db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    networks:
      - client-contacts
    environment:
      POSTGRES_PASSWORD: postgres

networks:
  client-contacts:
    driver: bridge
