spring:
  application:
    name: clientContacts
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#    url: jdbc:h2:mem:app-db
#    username:
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
#  profiles:
#    default: dev

springdoc:
  api-docs:
    path: /docs/v3/api-docs
  swagger-ui:
    path: /docs/swagger.html

logging:
  level:
    root: INFO
    web: DEBUG

base-url: /api
